### PR TITLE
Exercise CI under py3.11 & updates metadata/docs to include py3.11

### PR DESCRIPTION
**Pull request by mxr**
Per https://github.com/hakancelikdev/unimport/issues/297#issuecomment-1786896819

### CODE REVIEW

**Comment by hakancelikdev** [comment]
Can you check the libcst and other libraries within the scope of [this issue](https://github.com/hakancelikdev/unimport/issues/291)? If they have not yet released support for Python 3.11, we cannot do it either.

**Comment by hakancelikdev** [comment]
If the PRs you opened for 3.11 and 3.12 are not merged, will it prevent you from working?

I plan to open PR for these versions after extensive work.

**Comment by mxr** [comment]
I am happy to wait. Thanks.

Note that this PR exercises CI for `unimport` under py3.11 (formalizes "runs under" guarantees) and doesn't exercise "language version" functionality new to py3.11

**Comment by hakancelikdev** [comment]
Here is the new PR for that -> https://github.com/hakancelikdev/unimport/pull/304

**Pull request closed without merging**
